from tkinter import *
def fun1():
    print("It's Working!!")
win = Tk()
win.geometry("200x300")
menu = Menu(win)
win.config(menu=menu)
subMenu = Menu(menu)
menu.add_cascade(label="File", menu=subMenu)
subMenu.add_command(label="New Project..", command=fun1)
subMenu.add_command(label="New File..", command=fun1)
subMenu.add_command(label="Exit", command=quit)
editMenu = Menu(menu)
menu.add_cascade(label="Edit", menu=editMenu)
editMenu.add_command(label="Cut", command=fun1)
editMenu.add_command(label="Copy", command=fun1)
editMenu.add_command(label="Paste", command=fun1)
win.mainloop()
